### ISSUE TITLE
Sending with attachments results in empty message

### ISSUE THREAD

**Issue by ff2000** [imain/notmuch-vim#11]
... at least for some recipients. ;)

plugin/notmuch.rb#L295 adds a hack. This results in 2 additional empty text/plain parts (from the code I would have expected at least one text/html). The first one is the text-part that contains the message text. then comes the attachment, then the two empty text-parts.

The problem: notmuch-vim takes the first text part (m.find_first_text). But there are Mail clients that take another one. E.G. I sent a mail to a thunderbird-user, thunderbird took one of the empty parts. 

I did not set any sending-related options, so everything is default.

So the question is ( @imain ):
Is that hack really needed? I am using ruby mail-2.6.3, ruby-2.1.5, and those two lines commented out result in perfectly fine mails.
What issues did you get? Do you know your version (and others) that are broken? Then we can work around taking Mail::VERSION module.

**Comment by imain** [comment]
OK, let's try removing it then.  I was having problems with the mail not being designated 'multi-part' and the attachment wouldn't show up, just the text.  That was the only way I could find to make it work but maybe that's been fixed in a newer mail.rb.  You want to set up a PR to remove those lines?

**Comment by ff2000** [comment]
I just need to set up a test and play with the tags in the main-git-repo. There are some promising items in the changelog, like
"Message now adds multipart/mixed as the content type if nothing is set and there are parts to the message" (-> for version 2.0.3)
so I can leave the hack for versions that need it.
Do you have a history of your package updates, so you could at least say which version of mail definitely had that bug?

Or is it OK for you to pin a certain version of mail and in case an older version is installed simply abort sending or print a warning?

**Comment by ff2000** [comment]
Sleeping over it one night I think it is the best to simply remove the workaround. If there was a bug it seems to be fixed, it's up to distributions/maintainers/users to use working versions -> update regularly.

So I created a PR. Test it if it works for you now. For me it does work :)
