### ISSUE TITLE
Reply-to header not used when replying.

### ISSUE THREAD

**Issue by patternseek** [imain/notmuch-vim#14]
Hi,

I'm aware you're not the primary maintainer of notmuch-vim but you seem to have the most usable and maintained fork so I'm going to leave this here with the understanding that it's really not your job to fix it on the off-chance that it's something you want to handle! :)

Currently when a reply-to header is present in an email and you reply to it, the From: header is used instead.

Thanks for your work on notmuch-vim, you made it much more usable for me, especially with the attachments support.

**Comment by ff2000** [comment]
Doesn't the following commit fix the issue for you?
https://github.com/imain/notmuch-vim/commit/4287af7627768ae9498008b9c681fa243f016ed2

**Comment by patternseek** [comment]
Oops! Yes it does, sorry! I had a pretty recent checkout but I should have updated first.
Thanks!
