### ISSUE TITLE
Can't read emails with current master

### ISSUE THREAD

**Issue by patternseek** [imain/notmuch-vim#17]
Hi,

This appears to be related to the GPG PR. I've installed the mail-gpg gem but it doesn't help.

Without GPG enabled in .vimrc I get the following error when attempting to open a message, and a blank message area:

```
Error detected while processing function <SNR>15_search_show_thread..<SNR>15_show:
line    4:
NameError: uninitialized constant Mail::Gpg
```

and with GPG enabled I get this (and see only the From and Subject headers):

```
Error detected while processing function <SNR>15_search_show_thread..<SNR>15_show:
line    4:                                                                                                     
NameError: uninitialized constant Mail::Address::SPACE
```

Cheers!

**Comment by ff2000** [comment]
Thx for your report!
The issue is ruby evaluates `0` as true in contrast to other languages like C or python. This should be fixed now.

**Comment by patternseek** [comment]
That's sorted it, thanks!
