### ISSUE TITLE
How to save sent mails?

### ISSUE THREAD

**Issue by little-dude** [imain/notmuch-vim#22]
Edit: I actually had several questions so I edited this issue instead of opening multiple ones.

I'm switching from `sup` to `notmuch` with `notmuch-vim` as a plugin, and there are couple of things I can't figure: 
- how to save (and tag as "sent") the messages I send? `sup` was handling this by itself, but I'm not sure if it's something I should configure in `notmuch` itself or in `notmuch-vim`.
- how to fetch new emails? I first thought pressing `=` in a search view would fetch emails, but it appears I have to perform `notmuch new` by myself. Is there a mechanism to do that from `notmuch-vim`?
- by default, in the thread view, all the messages are expanded whereas the README says it should be folded. I get a `no fold found` error from vim when I try to fold them manually. Is that a bug or am I missing something?

**Comment by little-dude** [comment]
Looks like `notmuch-vim` actually does [save the sent mails and even tags them](https://github.com/imain/notmuch-vim/blob/master/plugin/notmuch.rb#L307). Weirdly I can't see them with `notmuch search --output=files tag:sent`

**Comment by ff2000** [comment]
On Wed, 26 Aug 2015 02:15:46 -0700, little-dude notifications@github.com wrote:

> I'm switching from sup to notmuch with notmuch-vim as a plugin, and one thing I can't figure is: how to save (and tag as "sent") the messages I send? sup was handling this by itself, but I'm not sure if it's something I should configure in notmuch itself or in notmuch-vim.

That should be handled automatically, as well.
It's done using "notmuch insert". By default it's stored in "Sent"
folder under the dir configured in ~/.notmuch-config by database.path.
You can configure if and where sent mails get stored via
g:notmuch_save_sent_locally and g:notmuch_save_sent_mailbox. See the
docs for further info.

**Comment by ff2000** [comment]
Just to be sure:
How did you install notmuch-vim? Did you clone it from this repo (manually or with an addon manager like vundle or neobundle)? Or did you use the one that comes with the notmuch release? Because your issues look like you are still running the bundled version instead of this fork.

Concerning your question with "fetching" new mails:
Yes, you have to use notmuch new to get new mails. "=" will just update the view. How do you receive new mails? I use offlineimap, that provides a postsync-hook. I use a tiny script that calls notmuch new and if there were new mails it runs some other commands. So I am always up-to-date :)

**Comment by little-dude** [comment]
> How did you install notmuch-vim?

Thanks for this... I'm using vundle and I started to install https://github.com/felipec/notmuch-vim. Then I changed to this repo, but just ran `PluginUpdate` so it did not update it.

Now that I have the correct version of the plugin, sent mails are stored indeed. I'm have some folding settings in my vimrc that does not play well with notmuch-vim though:

```
Error detected while processing function <SNR>46_search_show_thread..<SNR>46_show:
line    4:                                                                                                                                                                                                                                     
E350: Cannot create fold with current 'foldmethod'                                                                                                                                                                                             
E490: No fold found               
```

In my vimrc I use `foldmethod=syntax` so I'll have to look at how to have different settings for `notmuch-vim`.

```
    set foldenable                              " Enable folding
    set foldmethod=syntax                       " Automatic folding depending based on language
    set foldlevelstart=2                        " Start folding at lvl 2
```

> I use offlineimap, that provides a postsync-hook. I use a tiny script that calls notmuch new and if there were new mails it runs some other commands.

Awesome, thanks! I'm using offlineimap as well

Thanks a lot for your help!

**Comment by little-dude** [comment]
This did the trick:

```
autocmd FileType notmuch-show setlocal foldmethod=manual foldlevelstart=1
```
