### ISSUE TITLE
How to use msmtp to send mails?

### ISSUE THREAD

**Issue by little-dude** [imain/notmuch-vim#23]
I'd like to use `msmtp` to send emails. With `felipec/notmuch-vim` it worked by setting this:

```
let g:notmuch_sendmail = 'msmtp  -C ~/.config/mail/msmtp/msmtprc -t '
```

How can I achieve the same effect with this version of `notmuch-vim`? 

I first aliased `sendmail` to `msmtp  -C ~/.config/mail/msmtp/msmtprc -t` but :

```
Sending email via sendmail...sh: /usr/sbin/sendmail: No such file or directory
```

So I made `/usr/bin/sendmail` point to `/usr/bin/msmtp`, but:

```
Sending email via sendmail...sendmail: account default not found: no configuration file available
```

Last I tried to specify the config file by adding this, thinking it would somehow be converted to `--file ~/.config/mail/msmtp/msmtprc`:

```
let g:notmuch_sendmail_param = {
                \  'file': '~/.config/mail/msmtp/msmtprc',
        \  }
```

but I'm still getting the "no configuration file available".

For the record, the reason I'm not using the `smtp` method, is that this forces me to write my password in my vimrc, whereas in my msmtp conf file I can have the following:

```
passwordeval        python2 -c "import keyring; print keyring.get_password('email', 'little-dude')"
```

**Comment by ff2000** [comment]
On Wed, 26 Aug 2015 12:52:54 -0700, little-dude notifications@github.com wrote:

> I'd like to use `msmtp` to send emails. With `felipec/notmuch-vim` it worked by setting this:
> 
> ```
> let g:notmuch_sendmail_params = 'msmtp  -C ~/.config/mail/msmtp/msmtprc -t '
> ```
> 
> How can I achieve the same effect with this version of `notmuch-vim`? 
> 
> I first aliased `sendmail` to `msmtp  -C ~/.config/mail/msmtp/msmtprc -t` but :
> 
> ```
> Sending email via sendmail...sh: /usr/sbin/sendmail: No such file or directory
> ```
> 
> So I made `/usr/bin/sendmail` point to `/usr/bin/msmtp`, but:
> 
> ```
> Sending email via sendmail...sendmail: account default not found: no configuration file available
> ```
> 
> Last I tried to specify the config file by adding this, thinking it would somehow be converted to `--file ~/.config/mail/msmtp/msmtprc`:
> 
> ```
> let g:notmuch_sendmail_param = {
>                 \  'file': '~/.config/mail/msmtp/msmtprc',
>         \  }
> ```

```
let g:notmuch_sendmail_param = {
    \ 'arguments': '-C ~/.config/mail/msmtp/msmtprc',
\ }
```

might do the trick.
Here (Gentoo) msmtp symlinks itself to /usr/bin/sendmail. If tat is not
the case for you and you just don't want to create that symlink on your
own you can extend that setting by `'location': '/usr/bin/msmtp'`

For further reading have a look at https://github.com/mikel/mail/blob/master/lib/mail/network/delivery_methods/sendmail.rb
and https://github.com/mikel/mail/blob/master/lib/mail/message.rb

**Comment by little-dude** [comment]
It did the trick. I'm using archlinux which as a `msmtp-mta` package that does the linking between sendmail and msmtp. Thanks, once again!
